### ISSUE TITLE
[0617 토] 게시글 작성 기능 구현, 회원가입시 프로필 설정

### ISSUE THREAD

**Issue by yonainthefish** [FRONTENDSCHOOL5/final-21-WeMet21-Already29#20]
## Description
- 게시글 작성 :  테스트 토큰으로 게시글 업로드 api 받아 오는 부분 확인했습니다 경보님과 같이 확인 후 스타일링 작업 완료하여 금일 main merge 목표하고 있습니다 
- 회원가입시 프로필 설정:  html  작업 완료 후 이메일로 회원가입과 연결하여 feature 브랜치에 연결하는걸 목표로 하고 있습니다

## Todo 

- [ ] 게시글 작성 기존 오류 경보님과 공유 & 확인
- [ ] 게시글 작성 스타일링 
- [ ] 다중이미지 선택 코드 공부
- [ ] 입9팔9 전체 이미지 png 4배율 모음zip 공유

## ETC

기타 사항
