### ISSUE TITLE
[0620 화] 게시글 상세 페이지 UI와 기능 구현 중 

### ISSUE THREAD

**Issue by kyeongboo-coder** [FRONTENDSCHOOL5/final-21-WeMet21-Already29#24]
## Description

게시글 상세 페이지에 해당하는 기능 구현 중

## Todo 

- [ ] 댓글 작성 기능 구현 예정
- [ ] 게시글 상세 내용에 들어갈 내용과 기능 추가 구현 예정
- [ ] 게시글 작성 페이지 스타일 변경 예정 

## ETC

하은님과 함께 게시글 상세 페이지 구현 중입니다.
