### ISSUE TITLE
[0622 목] useInfiniteScroll 커스텀 훅 제작

### ISSUE THREAD

**Issue by KwanBeom** [FRONTENDSCHOOL5/final-21-WeMet21-Already29#47]
## Description
useInfiniteScroll 커스텀 훅 제작

쿼리스트링 형식으로 불러오는 API 요청이 있어 커스텀 훅 제작했습니다.

## Todo 
- [x] 컴포넌트 props로 fetch할 path 값 받아와 내부에서 비동기통신 처리 처리
- [x] Intersection Observer API 활용 무한 스크롤 처리
- [x] 컴포넌트 props로 Intersection Observer API observe 인자 전달
- [x] 반환 값 외부에서 다룰 수 있도록 return 값 지정

## ETC

const { getData, page, isLoading } = useInfiniteScroll("post/feed", pageEnd);
사용하실 때 첫번째 인자로 fetch할 path 주소 넘겨주시면 되고, 위 예시처럼 넘겨주시면 됩니다.
두번째 인자로는 스크롤 맨 끝에 있는 HTML 요소에  useRef 통해서 연결해서 넘겨주시면 됩니다.
보통 그냥 빈 div태그 넣고 레퍼런스 연결하는 것 같더라구요

반환값으로는 getData, page, isLoading 이 세가지가 있는데, 객체 형태로 return 되니까, 
디스트럭처링 하셔서 원하는 반환값만 뽑아서 사용하시면 될 거 같아요

getData : function
실행시키시면 Promise 객체 반환합니다. then 체이닝 하셔서 json 데이터 뽑아서 활용하시면 될 거 같습니다.

page : Number
현재 페이지가 어디인지 반환해줍니다. 
아까 인자로 전달한 pageEnd 요소에 도달했을 때 +1 되도록 로직이 짜여있습니다.
페이지 값이 변했을 때 getData 함수 실행할 수 있도록 코드 작성하시면 됩니다.

위 두개 반환값으로 무한 스크롤 구현하시려면 아래 코드 예시 참고해서 작성하시면 됩니다.
```jsx
const [posts, setPosts] = useState(null)
const [post, setPost] = useState(null)

  useEffect(() => {
    getData(page)
      .then((res) => res.json())
      .then((json) =>
        setPost((prev) => {
          if (prev) {
            return [...prev, ...json.posts];
          } else {
            return json.posts;
          }
        })
      );
  }, [page]);
```

isLoading : Boolean
